### PR TITLE
use abstract signup controller for registration process

### PR DESCRIPTION
**Pull request by DominikGuzei**
Implement abstract signup controller for custom registration process.
After this is merged you can remove the `RetryOrgRegistration` command – it is not used on the client-side anymore.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
lol … that's why im getting conflicts! :wink:

**Comment by rhyslbw** [comment]
shoot sorry my fault

**Comment by rhyslbw** [comment]
Considering this is a well defined controller it would be easiest to have a well defined interface and drop the need for generic `eventSubscriptions` since we have the mapping defined.

`onRequestSignupEvent()`?

**Comment by rhyslbw** [comment]
Also are the message traits not inherited from the base of `Space.accountsUi.SignupController` ?

**Comment by DominikGuzei** [comment]
ok good idea! you can take over here – im building the location editor atm. and don't want to switch all the time :wink:

**Comment by DominikGuzei** [comment]
Yes you can remove the traits … forgot that.

**Comment by rhyslbw** [comment]
Let's roll with this for the time being, as I have an API design that will require more time than we can spend right now.

**Comment by DominikGuzei** [comment]
Yeah, focussing on getting things done is highest priority now! We can refactor and improve later on

**Pull request merged**
