### PR TITLE
Chore/add auth checks

### PR DESCRIPTION
**Pull request by darko-mijic**

### CODE REVIEW

**Comment by rhyslbw** [comment]
Ok @darko-mijic let's just go with the triggers pattern now so we can ship the new version, as a lot has changed in my mind on managing local state, which would conflict with my earlier proposal. Looks good to me, is there any reason for still being WIP?

**Comment by darko-mijic** [comment]
@rhyslbw: I was planing to add security layer on the API level. But maybe we can ship this one and add that later.

**Comment by rhyslbw** [comment]
@darko-mijic might be best to just do that in this PR since it's considered basic security and we won't be shipping until both are done. I can add this in then we can merge

**Comment by darko-mijic** [comment]
ok

**Comment by rhyslbw** [comment]
@darko-mijic
- Branch updated with the changes from _develop_ most notably support for the latest Space APIs
- Space.messaging.Api security added
- All deps have been bumped

We're ready to merge this in, but before deploying this new version to sachspenden.online is https://github.com/meteor-space/event-sourcing/issues/67. Did you have a chance to work on this?

**Pull request closed without merging**
