### PR TITLE
Feature/improve form submit handling

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds minimal error handling / form submitting logic so that admins can't submit wrong stuff where it is important (eg: registration) and avoid double-submits everywhere.
- Minimal error handling in registration form
- Register button disabled after submit
- add Locations / Appeals forms are reset after submit

For the registration this PR also removes the org registration store, as we don't really need it. Currently we have no way to transport good domain error messages to the client anyway.

### CODE REVIEW

**Comment by rhyslbw** [comment]
Should probably also protect against a blank appeal title

**Comment by DominikGuzei** [comment]
Yeah later on – at the moment that's not so important because the admin can edit the title after creation. I just fixed / secured those things that cannot be undone.

**Comment by rhyslbw** [comment]
I'm not able to edit the blank title after making the appeal public

**Comment by DominikGuzei** [comment]
Ah thanks, that's an actual bug in the edit appeal form :wink:

**Pull request merged**
