### PR TITLE
Nests libraries under lib directory in base package

### PR DESCRIPTION
**Pull request by rhyslbw**
I think this is a key concept, as although we are building these up at the same time with the implementation, they are then being accessed as a library to create instances of events, commands, and value objects.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Ok, what else will be in the base package? maybe the whole package should be called library?

**Comment by rhyslbw** [comment]
well the only other thing currently is the namespace, which violates this. I see your point, but it's like the idea of using  /server in a package with server-only files

**Comment by DominikGuzei** [comment]
I still don't see the big benefit – `lib` is always an anti pattern for me because it's like `manager`, just a generic term that has no real meaning.

**Comment by rhyslbw** [comment]
ok, it's an extra layer of categorisation I guess that's not needed

**Pull request closed without merging**
